# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy (node.js)

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build
      run: |
        rm -rf docs/
        npm run build
        mv build docs
        git add docs/
    - name: Commit and push
      run: |
        git config --global user.email ${{secrets.SECRET_EMAIL}}
        git config --global user.name ${{secrets.SECRET_NAME}}
        git remote set-url origin https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/${{secrets.SECRET_NAME}}/${{secrets.SECRET_REPO}}.git
        git commit -m "Update docs folder"
        git push origin master
